### ISSUE TITLE
GreenDaoManager没有调用build初始化DBHander

### ISSUE THREAD

**Issue by LeoYu007** [jeanboydev/Android-Architecture#3]
RxJava分支上，GreenDaoManager没有调用build初始化DBHander，其他分支没确认是否有次问题

**Comment by LeoYu007** [comment]
还有个问题，NetHandler中doSync方法是同步返回结果，设计成如下比较合理：
ResponseData\<B\> doSync(RequestParams\<P\> requestValues);

**Comment by jeanboydev** [comment]
@LambertCoding GreenDaoManager的确没有初始化，漏掉了，NetHandler中doSync中建议很不错，十分感谢
